### ISSUE TITLE
Conceptual 

### ISSUE THREAD

**Issue by dobrosketchkun** [cakenggt/Library-Of-Pybel#4]
I touch some conceptual misunderstanding with me and this implementation.

Say, I want to find not only a book with a page with some text, but a book with two pages in tandem (e.g. my text is too long to fit in one page). So, what I should do? I try to find some book with one page (with first part of my long text) and then check the page after it. If it's not what I want and doesn't include the remain of my text, I'll try another book and so on. 

But what I see? All of those second pages is identical. 

I know, the number of books with exactly 4 typo permutations is 40,960,672,578,684,980,713,193,472,000. May be, I think, it's just coincidence or just a tendency to find look-a-like books as artefact of implementation?

So I wrote a script to check a similarity of those books:
https://gist.github.com/dobrosketchkun/7e7fa6782ef0017c3e42e97687f39582
All of it was the same, exact 100% similarity.

But there are no identical books in The Library!

May be I'm wrong in script implementation or just don't understand how the actual python implementation works?

**Comment by cakenggt** [comment]
You will have a very hard time of finding two pages in order. The library implementation is only set up for single page search, in fact that is how the library generates pages. In order to search for an entire book, the length of the hex of a book would have to be the same as the total number of characters in that book.

I looked at your script and it looks like you aren't actually looking through the pages in the second loop. Specifically, look at the `i` in line 19: that is never used to actually increase the page number.

**Comment by cakenggt** [comment]
I am closing this issue
